### ISSUE TITLE
charset-labels.txt file not found

### ISSUE THREAD

**Issue by hanouel** [codeaway23/number-plate-detection#1]
I tried to execute the code bby following the mentionned steps, but while execution this script get_tf_records.py an error is generated: FileNotFoundError: [Errno 2] No such file or directory: 'charset-labels.txt'
How can I generated this file? 
Thanks.

**Comment by codeaway23** [comment]
I have added the file in my tensorflow models fork. I added the link to the charset-labels.txt file in the README file. You can access it now.

**Comment by hanouel** [comment]
thank you
