### ISSUE TITLE
issue about model.cpkt-3000 in common_flags.py

### ISSUE THREAD

**Issue by parthplc** [codeaway23/number-plate-detection#2]
Not able to understand how did you get the model.ckpt-3000 even before training in common_flags.py

**Comment by codeaway23** [comment]
I did not. Before you begin training, change the default checkpoint flag to None. Once you have trained the model, you can change the checkpoint path to your latest checkpoint in the common flags file or run the inference script through command line and specify the checkpoint path explicitly.

**Comment by parthplc** [comment]
Thanks!! Its working properly now!!
